/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import sop_corba.ClienteInt;
import sop_corba.ServidorInt;

/**
 *
 * @author HSVSTT2
 */
public class GUIClienteChat extends javax.swing.JFrame {

    
    private ServidorInt svrchat;        
    private ClienteInt objcllbck;
    private String nombre;
    
    public GUIClienteChat(ServidorInt svrchat,String nombre) {
        initComponents();
        this.svrchat=svrchat;
        
        this.nombre=nombre;
        this.jlabelclienteChat.setText(nombre);
        fijarContacto(nombre);
    }
        
    public void asociarObjetoRemoto(ClienteInt objcllbck)
    {
        this.objcllbck=objcllbck;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jlabelclienteChat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbuttonenviar = new javax.swing.JButton();
        jbuttonsalir = new javax.swing.JButton();
        jtextareamsg = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextareachat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtextareacontacto = new javax.swing.JTextArea();
        jLabelUsuariosConectados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Chat con el administrador del sistema");

        jLabelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNombreUsuario.setText("Usuario:");

        jlabelclienteChat.setText("jLabelUsuarioConectado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombreUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jlabelclienteChat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTitulo)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreUsuario)
                    .addComponent(jlabelclienteChat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 153));

        jbuttonenviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbuttonenviar.setText("Enviar");
        jbuttonenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonenviarActionPerformed(evt);
            }
        });

        jbuttonsalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbuttonsalir.setText("Salir");
        jbuttonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonsalirActionPerformed(evt);
            }
        });

        jtextareamsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtextareamsgKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextareamsg, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbuttonenviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonsalir)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jtextareamsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonenviar)
                    .addComponent(jbuttonsalir))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(0, 0, 153));

        jtextareachat.setColumns(20);
        jtextareachat.setRows(5);
        jScrollPane1.setViewportView(jtextareachat);

        jtextareacontacto.setColumns(20);
        jtextareacontacto.setRows(5);
        jScrollPane2.setViewportView(jtextareacontacto);

        jLabelUsuariosConectados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUsuariosConectados.setText("Usuarios conectados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuariosConectados))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabelUsuariosConectados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonsalirActionPerformed
        svrchat.desconectarCliente(objcllbck, nombre);
	System.exit(0);
    }//GEN-LAST:event_jbuttonsalirActionPerformed

    private void jbuttonenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonenviarActionPerformed
        svrchat.enviarMensaje(nombre,jtextareamsg.getText());
	jtextareamsg.setText("");
    }//GEN-LAST:event_jbuttonenviarActionPerformed

    private void jtextareamsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextareamsgKeyPressed
        jbuttonenviar.setEnabled(true);  
    }//GEN-LAST:event_jtextareamsgKeyPressed

    public void fijarTexto(String nombreUsuario,String msg) {
        System.out.println("Invocando fijarTexto()...");
        //jtextareachat.setEnabled(true);
        try { 
            jtextareachat.append(nombreUsuario + " escribió:\n" + msg +"\n");
        } catch(Exception ex){}    	
            //TODO add your code for jbuttonHistorial.actionPerformed
    }
	
    public void fijarContacto(String nombre) {
        System.out.println("Invocando fijarContacto()...");
        //jtextareachat.setEnabled(true);
        try {                  
              jtextareacontacto.append(nombre + " en linea\n");
        } catch(Exception ex){}    	   
            //TODO add your code for jbuttonHistorial.actionPerformed
    }
	
    public String obtenerNombre(){
            return this.nombre;
    }

    public void borrarLista()
    {
        jtextareacontacto.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuariosConectados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbuttonenviar;
    private javax.swing.JButton jbuttonsalir;
    private javax.swing.JLabel jlabelclienteChat;
    private javax.swing.JTextArea jtextareachat;
    private javax.swing.JTextArea jtextareacontacto;
    private javax.swing.JTextField jtextareamsg;
    // End of variables declaration//GEN-END:variables
}
