package sop_corba.ServidorIntPackage;


/**
* sop_corba/ServidorIntPackage/DatosCliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 1 de diciembre de 2024 03:01:22 PM COT
*/

public final class DatosCliente implements org.omg.CORBA.portable.IDLEntity
{
  public String usuario = null;

  public DatosCliente ()
  {
  } // ctor

  public DatosCliente (String _usuario)
  {
    usuario = _usuario;
  } // ctor

} // class DatosCliente
