package sop_corba;


/**
* sop_corba/ServidorInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 1 de diciembre de 2024 03:01:22 PM COT
*/

public interface ServidorInt extends ServidorIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServidorInt
