package sop_corba;


/**
* sop_corba/ServidorIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 1 de diciembre de 2024 03:01:22 PM COT
*/

public interface ServidorIntOperations 
{
  boolean registrarCliente (sop_corba.ClienteInt objCallback, String usuario);
  void enviarMensaje (String usuario, String mensaje);
  void calificarAtencion (String usuario, float calificacion);
  float obtenerPromedioCalificaciones ();
  String obtenerApreciacion ();
  sop_corba.ServidorIntPackage.DatosCliente[] obtenerUsuariosConectados ();
  boolean desconectarCliente (sop_corba.ClienteInt objcllbck, String usuario);
} // interface ServidorIntOperations
